### PR TITLE
Feature/pinned items

### LINKED ISSUE #94: Improve channel info panel toggling
https://github.com/SpaceTalk/SpaceTalk/blob/develop/client/views/channel-info/channel-info.html#L10

Is there a way to not use checkboxes? I find that sometimes I can't get it to expand unless I click just the right spot. I should be able to click that entire block where the heading is to expand it.

### PR DESCRIPTION
**Pull request by adamdawkins**
Delivers #65, Fixes #94.
## Features
- pin a message functionality
- un-pin a message (from the channel body only, not yet in the pinned items panel) functionality
- When a message is pinned, channel info bar opens, and pinned items panel is open
- Added App object for keeping `ReactiveVar` states for the open/close of the Channel Info Bar
- Re-worked CSS of Channel Info bar, partly to simplify the `ReactiveVar` tracking (checkboxes are a nightmare to work with in js), and partly for #94.
## For opinion / to do
- Un-pin from channel info bar ( Though I think we can release without this)
- The sweet alert for un-pinning a message is definitely overkill, but I can't think of a good alternative for now.

### CODE REVIEW

**Comment by nabiltntn** [comment]
Do you call un-pin message after message delete ?

**Comment by timbrandin** [comment]
There's an exception when starting it:

Exception from sub channelPinnedMessages id SnmqprnxDW9Xe4d2q Error: Exception while polling query {"collectionName":"messages","selector":{"_id":{}},"options":{}}: Can't canonicalize query: BadValue $in needs an array

**Comment by dstollie** [comment]
@adamdawkins Im really look forward to this functionality, can you make it ready to rock on the current develop version?

**Comment by adamdawkins** [comment]
@dstollie , @timbrandin I've fixed that error message now.

@nabiltntn I didn't, I do now.

**Comment by dstollie** [comment]
@adamdawkins im going to check it out now!

**Comment by dstollie** [comment]
@adamdawkins I just did some style changes and fixed the issue when when the channel-info should be scrollable.

One issue:
Click on one of the channel info titles, it doesn't cause the item to dropdown. The only way pinned messages are getting showed is when a message get pinned.

Also I think it should be possible whenever the user click on a pinned message he gets navigated to the message inside the channel itself. But I dont know if this would be something for this PR or a new one

**Pull request merged**
