### PR TITLE
PR for #75 : Set a purpose for the channel , display the creation date and username of creator

### PR DESCRIPTION
**Pull request by nabiltntn**

### CODE REVIEW

**Comment by rclai** [comment]
https://github.com/SpaceTalk/SpaceTalk/issues/77

Please, thanks.

Good work by the way.

**Comment by nabiltntn** [comment]
What should i do excatly ? i didnt understand the title of #77

**Comment by rclai** [comment]
Your code is not formatted properly according to the Meteor style guide.

**Comment by nabiltntn** [comment]
AHA, will be fixing that

**Comment by rclai** [comment]
Right now there's a small merge conflict with `develop` on the CSS. So can you reconcile those, they should not be too hard. Also, when you merge in `develop` you'll notice that Meteor's gonna complain about not having a `settings.json` file, so just run the app with `meteor run --settings=settings.json` after you merged it in.

I think that the textarea for setting the purpose, while it looks pretty nice, should show up right underneath where you clicked 'set the current purpose of the channel'.

The three channel info sections (About this channel, pinned items, members), when they're collapsed, have uneven vertical padding.

Other than that, I like how you set up the area for the channel purpose.

CC @dstollie @timbrandin @dmitrijs-balcers

**Comment by timbrandin** [comment]
I've improved on this solution and are tracking it in #92

**Pull request merged**
