### PR TITLE
added simpel shell script to make running spacetalk so much simpler

### PR DESCRIPTION
**Pull request by dstollie**

### CODE REVIEW

**Comment by timbrandin** [comment]
How do I use it? :P

**Comment by mpowaga** [comment]
`./run` from the console?

**Comment by timbrandin** [comment]
I got this output when I did the above @mpowaga

```
$ ./run
\e[94mStarting the almighty SpaceTalk
[[[[[ ~/Projects/SpaceTalk ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
```

**Comment by dstollie** [comment]
yeh just run it as `./run` or `sh run` simple as it is!

**Comment by rclai** [comment]
Update the instructions in the README.md as well (Windows users too!).

**Comment by timbrandin** [comment]
I suggest we skip this and also settings.json because we don't have any info in it yet. You shouldn't need to start with settings.json anyway. Check this out, the value is null; https://github.com/SpaceTalk/SpaceTalk/blob/feature/package-structures/settings.json#L3

**Comment by dstollie** [comment]
If you really want to use iframely you should give an API key. now you are getting some really unwanted errors. Imo using the settings.json is the best an most straightforward solution to place the used api keys. Im currently not working a windows machien and bash is not supported under windows so someone else has to create the batch script

**Comment by rclai** [comment]
We should make it so that a settings.json file is not required to run if you don't have an API key.

**Comment by dstollie** [comment]
If not settings are given Spacetalk has to be clever enough to load the default settings.json file in by himself.. Ill work on this

**Pull request closed without merging**
