### PR TITLE
Mongo queries optimization when used to check if document exists

### PR DESCRIPTION
**Pull request by yanisIk**
Using !Collection.find(id).count() instead of !Collection.findOne(id) when we only need to check if the document exists.

More information about that here : 
https://blog.serverdensity.com/checking-if-a-document-exists-mongodb-slow-findone-vs-find/

### CODE REVIEW

**Comment by dstollie** [comment]
Thanks @yanisIk! I didn't know that one

**Comment by timbrandin** [comment]
Awesome! :+1:

**Comment by rclai** [comment]
Are you actually allowed to do: `Channels.find(itemId)`? I thought you have to do `{ _id: itemId }` for `find`s.

**Comment by timbrandin** [comment]
Hmm, did this even work before? It was like that before the change.

**Comment by yanisIk** [comment]
@rclai When you don't specify a field, the selector uses the _id field by default.

**Comment by rclai** [comment]
Okay cool.

**Comment by timbrandin** [comment]
Wow, I did not know that! haha that's useful

2015-08-04 2:19 GMT+02:00 Richard Lai notifications@github.com:

> Okay cool.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SpaceTalk/SpaceTalk/pull/127#issuecomment-127439889.

## 

Cheers,
// Tim Brandin @timbrandin https://twitter.com/#!/timbrandin
http://timbrandin.com
http://studiointeract.com

**Pull request merged**
