### PR TITLE
Add log in redirect and better logout click event.

### PR DESCRIPTION
**Pull request by samwightt**
I added a simple redirect helper so that on login the user will be redirected to /teams/public. I also removed the class from the a tag in the sidebar and added it to the entire lower div itself. That way if the user accidentally clicks a bit to the left or to the right, they will still be logged out.

### CODE REVIEW

**Comment by samwightt** [comment]
Alright, it's fixed.

**Comment by dstollie** [comment]
thanks man, got it merged

**Comment by samwightt** [comment]
Awesome!

**Comment by rclai** [comment]
Thanks @samuelwight.

**Pull request merged**
