### PR TITLE
Add indication who is typing

### PR DESCRIPTION
**Pull request by mpowaga**

### CODE REVIEW

**Comment by rclai** [comment]
They had a brief discussion of possibly merging some functionality together in both packages but don't see that happening anytime soon. I think just having both will do for now.

@timbrandin @dstollie thoughts?

**Comment by timbrandin** [comment]
I'm ok with both, we can improve this later :) @rclai

**Comment by timbrandin** [comment]
Alright, cool! Apart from that we have two presence packages this works and follows the code standards set up, I'm merging it.

**Comment by dstollie** [comment]
@mpowaga whenever the message is send the is typing message is still shown for a few seconds. Could you fix this?

**Pull request merged**
