### PR TITLE
left sidebar currently shows all users and when a user is selected th…

### PR DESCRIPTION
**Pull request by dstollie**
…e direct channel will be created automtically. also added the @username route part

see trello items:
https://trello.com/c/94DTGBVN
https://trello.com/c/6Ln5oLWN

### CODE REVIEW

**Comment by timbrandin** [comment]
It doesn't change messages when you switch user. I guess there's a remaining bug

**Comment by timbrandin** [comment]
@dstollie could you have a look?

**Comment by timbrandin** [comment]
Could we do private message routes without the @-sign? it seems strange to have that in the URL.
I would also prefer it not to use "channels" in the route, how about "users" instead?

**Comment by dstollie** [comment]
we should discuss this another time I think, changing this would be a pretty big change. I just looked at how slack did this

**Comment by rclai** [comment]
We need a totally separate route for direct messages `user/username` or something like that.

At this point, it's getting to a point where we're now needing to hide certain things on the channel component based on whether it's a direct message or channel and later on that's only going to get more cumbersome to maintain. With the current structure that we should be able to re-use some of the components to use in a `DirectMessages` component, or something like that.

~~Data-wise, we should just put a field on `Messages` called `toUserId` and our publication will be:~~

<del>
```js
Meteor.publish('directMessages', function (toUserId /* or username rather */) {
  // Do some checks
  if (this.userId && this.userId !== toUserId && Meteor.users.findOne(toUserId)) {
    return Messages.find({ 
      userId: { 
        $in: [this.userId, toUserId] 
      }, 
      toUserId: { 
        $in: [this.userId, toUserId] 
      } 
    });
  }
  this.ready();
});
```
</del>

~~We can leave what @queso has done already to rather have **private channel** functionality, keeping the `allowedUsers` field but just axe the `direct` field on `Channels`.~~

Let me know what you think.

**Comment by queso** [comment]
@rclai what are you hoping to gain? We already have a pub/sub setup for channels and messages, I think rendering the UI differently is a UI concern and not a pub/sub concern.

**Comment by rclai** [comment]
You're right, never mind the data change. But I think the channel component and its route do need a mitosis. I think a base component would help in sharing functionality between the two (like the auto-scroll down).

**Comment by timbrandin** [comment]
Looking good! :)

**Pull request merged**
