### PR TITLE
Added Docker support. Run 'docker build -t yourname/spacetalk .' to bundle SpaceTalk into a production-ready Docker image

### PR DESCRIPTION
**Pull request by chriswessels**
Please see: https://trello.com/c/NXdReUCv/64-docker-support-for-easily-running-in-production

### CODE REVIEW

**Comment by timbrandin** [comment]
Looks good, I'd love a preview how to set it up. :)

**Comment by rclai** [comment]
@chriswessels can you add to the README about some documentation on how to do this if it's not too cumbersome? I haven't done much with Docker lately.

**Comment by chriswessels** [comment]
@rclai @timbrandin I'll put something together in the next few days.

**Comment by rclai** [comment]
Thanks.

**Comment by dstollie** [comment]
Looks like this one aint get updated, so close

**Pull request closed without merging**
