### PR TITLE
Feature/users online status (sidebar)

### PR DESCRIPTION
**Pull request by kevincharm**
Pretty basic, just ported to Blaze Components but my first time using. Let me know if I'm doing it wrong @rclai

### CODE REVIEW

**Comment by rclai** [comment]
You're going on the right track with Blaze Components. If you want to access the parent component (`LeftSidebar`) instance in the `DirectMessagesForm` component for whatever reason, you can do `this.parentComponent()`.

**Comment by kevincharm** [comment]
Thanks @rclai I'll change the code to access the parent instead.

**Comment by dstollie** [comment]
@hellstad i merged you stuff with the develop.. once ur done wiht adding new features please tell us so we can merge.. I made som changes you can check them by yourself

**Comment by kevincharm** [comment]
@dstollie does this need any more features? I think direct messages are already being worked on.

**Pull request merged**
