### PR TITLE
Display channel info by clicking info icon in the header

### PR DESCRIPTION
**Pull request by nabiltntn**

### CODE REVIEW

**Comment by dstollie** [comment]
I checked out your changes but I don't see the point of an empty channel info sidebar. It currently looks "not finished" are you still working on this?

The channel info sidebar also pops when it enters and slides back when it leaves could you also make it sliding when it enters?

currently I only see some text with a white container incomming would be better if you make it it more like an incomming container (using border-left or something).

lastly, could you create a simple > button which slides teh container back?

You did a nice job but I think there has to be some work done before mergning

**Comment by nabiltntn** [comment]
I made some changes, can you check again and merge the pull request

**Comment by dstollie** [comment]
@nabiltntn I just nicen up the homepage desgin #35 and restructured the scss files for better maintainability. Could you merge your stuff with the current develop and try to put your sass changes in the right sass file?

**Comment by rclai** [comment]
Were you going to show who's in the channel as per [the Trello card](https://trello.com/c/ZP72d2GK/12-channel-members)?

**Comment by nabiltntn** [comment]
Merge done, could you check please

**Comment by nabiltntn** [comment]
@rclai the idea is to prepare the field before implementing such feature

**Comment by rclai** [comment]
@nabiltntn looks very nice. Thanks.

**Pull request merged**
