### PR TITLE
Fix #119 : User can change message timestamp and userId

### LINKED ISSUE #119: User can change message timestamp and userId
Just wanted to point out that it's currently possible to change a message's timestamp and userId via the browser console on http://spacetalk.meteor.com/

### PR DESCRIPTION
**Pull request by nabiltntn**

### CODE REVIEW

**Comment by nabiltntn** [comment]
Right, because it's aslo possible to mess around with $unset, or full document change.

Moving message update to a method is not enough, because you can still use Messages.update from browser console.

**Comment by rclai** [comment]
Because you need to take out the `allow` rule for `update`. Take [all this](https://github.com/nabiltntn/SpaceTalk/blob/2f09399fc44537b4e74711cf6febf77f77077fc2/lib/messages.js#L44-L48) out.

**Comment by nabiltntn** [comment]
so collections-hooks takes care of such situation so using fieldnames in before.update hook gives the name of fields used in all update operators like $set , $unset , etc 
https://github.com/matb33/meteor-collection-hooks/blob/master/update.js#L108-L134

Document replace is not allowed by meteor anyway.

**Comment by dstollie** [comment]
@nabiltntn have you finished working on this issue?

**Comment by nabiltntn** [comment]
@dstollie For me it's OK , i have done the changes after @rclai comments. Now , i am sur to handle all cases of updates.

**Comment by dstollie** [comment]
@nabiltntn thanks for your effort, keep up the good work!

**Pull request merged**
