### PR TITLE
Feature/theme improvements

### PR DESCRIPTION
**Pull request by timbrandin**
Improved:
- Frontpage
- Background
- Colors
- Dropdowns
- Icons

### CODE REVIEW

**Comment by dstollie** [comment]
The text editing button is in the far right... can you replace it next the the username - date ?

**Comment by timbrandin** [comment]
This way makes more sense when messages are grouped, as there isn't any username on every row

Skickat från min iPhone

**Comment by rclai** [comment]
Yeah, that's one of the things I don't like about Slack, the edit button is super invisible all the way to the right.

**Comment by timbrandin** [comment]
The solution for the edit link is in #88

**Pull request merged**
