### PR TITLE
Emoji autocomplete

### PR DESCRIPTION
**Pull request by jonearley**
Added emoji autocomplete based on shortname. Adapted from emojione shortname autocomplete, http://git.emojione.com/demos/autocomplete.html. Related to Issue #68.

Preview:

emoji autocomplete

### CODE REVIEW

**Comment by nabiltntn** [comment]
+1 i was thinking about it too :) , but i think it would be better to have an icon that displays all the list of emoji ( or tabs with categories) and the user can choose. it's hard to remember all names

**Comment by dstollie** [comment]
Nice job on this one! Didnt expect this feature comming that soon. Ill check this out tomorrow

**Comment by timbrandin** [comment]
Someone needs to fix the merge conflicts with develop for this. I'd love to have it in for 0.1!!

**Comment by timbrandin** [comment]
I'm trying to get it to work now.

**Pull request merged**
